<?php
// @formatter:off

namespace PHPSTORM_META {

   /**
    * PhpStorm Meta file, to provide autocomplete information for PhpStorm
    *
    * @author Barry vd. Heuvel <barryvdh@gmail.com>
    * @see https://github.com/barryvdh/laravel-ide-helper
    */
    override(new \Illuminate\Contracts\Container\Container, map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));
    override(\Illuminate\Container\Container::makeWith(0), map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));
    override(\Illuminate\Contracts\Container\Container::get(0), map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));
    override(\Illuminate\Contracts\Container\Container::make(0), map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));
    override(\Illuminate\Contracts\Container\Container::makeWith(0), map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));
    override(\App::get(0), map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));
    override(\App::make(0), map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));
    override(\App::makeWith(0), map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));
    override(\app(0), map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));
    override(\resolve(0), map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));
    override(\Psr\Container\ContainerInterface::get(0), map([
        '' => '@',
            'App\Contracts\BuildersMenuHelperContract' => \App\Helpers\BuildersMenuHelper::class,
            'App\Contracts\BuildersServiceContract' => \App\Services\BuildersServiceService::class,
            'App\Contracts\EnvironmentsMenuHelperContract' => \App\Helpers\EnvironmentsMenuHelper::class,
            'App\Contracts\EnvironmentsServiceContract' => \App\Services\EnvironmentsService::class,
            'App\Contracts\JsonConfigServiceContract' => \App\Services\JsonConfigServiceService::class,
            'Illuminate\Cache\RateLimiter' => \Illuminate\Cache\RateLimiter::class,
            'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
            'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
            'Illuminate\Contracts\Debug\ExceptionHandler' => \NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::class,
            'Illuminate\Foundation\Mix' => \Illuminate\Foundation\Mix::class,
            'Illuminate\Foundation\PackageManifest' => \Illuminate\Foundation\PackageManifest::class,
            'LaravelZero\Framework\Contracts\Providers\ComposerContract' => \LaravelZero\Framework\Providers\Composer\Composer::class,
            'LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository' => \LaravelZero\Framework\Providers\CommandRecorder\CommandRecorderRepository::class,
            'NunoMaduro\Collision\Provider' => \NunoMaduro\Collision\Provider::class,
            'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
            'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
            'cache' => \Illuminate\Cache\CacheManager::class,
            'cache.store' => \Illuminate\Cache\Repository::class,
            'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
            'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
            'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
            'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
            'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
            'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
            'events' => \Illuminate\Events\Dispatcher::class,
            'files' => \Illuminate\Filesystem\Filesystem::class,
            'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
            'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
            'log' => \Psr\Log\NullLogger::class,
            'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
            'translation.loader' => \Illuminate\Translation\FileLoader::class,
            'twig.loader' => \DinhQuocHan\Twig\TwigLoader::class,
            'view' => \Illuminate\View\Factory::class,
            'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
            'view.finder' => \Illuminate\View\FileViewFinder::class,
        ]));


    override(\Illuminate\Foundation\Testing\Concerns\InteractsWithContainer::mock(0), map(["" => "@&\Mockery\MockInterface"]));
    override(\Illuminate\Foundation\Testing\Concerns\InteractsWithContainer::partialMock(0), map(["" => "@&\Mockery\MockInterface"]));
    override(\Illuminate\Foundation\Testing\Concerns\InteractsWithContainer::instance(0), type(1));
    override(\Illuminate\Foundation\Testing\Concerns\InteractsWithContainer::spy(0), map(["" => "@&\Mockery\MockInterface"]));
    override(\Illuminate\Support\Arr::add(0), type(0));
    override(\Illuminate\Support\Arr::except(0), type(0));
    override(\Illuminate\Support\Arr::first(0), elementType(0));
    override(\Illuminate\Support\Arr::last(0), elementType(0));
    override(\Illuminate\Support\Arr::get(0), elementType(0));
    override(\Illuminate\Support\Arr::only(0), type(0));
    override(\Illuminate\Support\Arr::prepend(0), type(0));
    override(\Illuminate\Support\Arr::pull(0), elementType(0));
    override(\Illuminate\Support\Arr::set(0), type(0));
    override(\Illuminate\Support\Arr::shuffle(0), type(0));
    override(\Illuminate\Support\Arr::sort(0), type(0));
    override(\Illuminate\Support\Arr::sortRecursive(0), type(0));
    override(\Illuminate\Support\Arr::where(0), type(0));
    override(\array_add(0), type(0));
    override(\array_except(0), type(0));
    override(\array_first(0), elementType(0));
    override(\array_last(0), elementType(0));
    override(\array_get(0), elementType(0));
    override(\array_only(0), type(0));
    override(\array_prepend(0), type(0));
    override(\array_pull(0), elementType(0));
    override(\array_set(0), type(0));
    override(\array_sort(0), type(0));
    override(\array_sort_recursive(0), type(0));
    override(\array_where(0), type(0));
    override(\head(0), elementType(0));
    override(\last(0), elementType(0));
    override(\with(0), type(0));
    override(\tap(0), type(0));
    override(\optional(0), type(0));

}
